"""Minor changes in tables

Revision ID: 35d0080a250f
Revises: 17280d3090c2
Create Date: 2024-10-28 01:09:44.832163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d0080a250f'
down_revision: Union[str, None] = '17280d3090c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Ratings_product_id_key', 'Ratings', type_='unique')
    op.drop_constraint('Ratings_user_id_key', 'Ratings', type_='unique')
    op.drop_constraint('Reviews_product_id_key', 'Reviews', type_='unique')
    op.drop_constraint('Reviews_user_id_key', 'Reviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Reviews_user_id_key', 'Reviews', ['user_id'])
    op.create_unique_constraint('Reviews_product_id_key', 'Reviews', ['product_id'])
    op.create_unique_constraint('Ratings_user_id_key', 'Ratings', ['user_id'])
    op.create_unique_constraint('Ratings_product_id_key', 'Ratings', ['product_id'])
    # ### end Alembic commands ###
